# Generated by Django 5.0.6 on 2024-08-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('opta', models.CharField(max_length=50)),
                ('optb', models.CharField(max_length=50)),
                ('optc', models.CharField(max_length=50)),
                ('optd', models.CharField(max_length=50)),
                ('correctanswer', models.IntegerField()),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
