# Generated by Django 5.0.6 on 2024-08-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('dateofbirth', models.CharField(max_length=100)),
                ('male', models.CharField(max_length=20)),
                ('female', models.CharField(max_length=20)),
                ('single', models.CharField(max_length=20)),
                ('married', models.CharField(max_length=20)),
                ('presentaddress', models.CharField(max_length=100)),
                ('permanentaddress', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('sql', models.CharField(max_length=100)),
                ('java', models.CharField(max_length=100)),
                ('html', models.CharField(max_length=100)),
                ('python', models.CharField(max_length=100)),
                ('css', models.CharField(max_length=100)),
                ('bootstrap', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admission',
            },
        ),
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'phonebook',
            },
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='booltitle',
            new_name='booktitle',
        ),
    ]
