# Generated by Django 5.0.6 on 2024-08-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_bankbook'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankbook',
            table='bank',
        ),
    ]
