# Generated by Django 5.0.6 on 2024-08-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_bankbook_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankbook',
            table='bankbook',
        ),
    ]
