# Generated by Django 5.0.6 on 2024-08-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_collage_delete_bankbook'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admission',
            table='admissions',
        ),
    ]
