# Generated by Django 5.0.6 on 2024-08-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_form'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='form',
            table='froms',
        ),
    ]
