# Generated by Django 5.0.6 on 2024-08-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_marksheet'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marksheet',
            table='results',
        ),
    ]
